---
apiVersion: v1
kind: Service
metadata:
  name: git-http-backend
  namespace: git
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: git-http-backend
  sessionAffinity: None
  type: ClusterIP
